// <auto-generated />
using System;
using FlashFlights.Catalog.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlashFlights.Catalog.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260905123706_AddReferenceFare")]
    partial class AddReferenceFare
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("FlashFlights.Catalog.Domain.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DepartureAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FlashPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ReferenceFare")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SaleEndsAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SaleStartsAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SaleStartsAt");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("FlashFlights.Catalog.Domain.FlightSeatCounts", b =>
                {
                    b.Property<Guid>("FlightId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfirmedSeats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeldSeats")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastMovementAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("INTEGER");

                    b.HasKey("FlightId");

                    b.ToTable("FlightSeatCounts");
                });

            modelBuilder.Entity("FlashFlights.Catalog.Domain.FlightSeatCounts", b =>
                {
                    b.HasOne("FlashFlights.Catalog.Domain.Flight", "Flight")
                        .WithOne("SeatCounts")
                        .HasForeignKey("FlashFlights.Catalog.Domain.FlightSeatCounts", "FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("FlashFlights.Catalog.Domain.Flight", b =>
                {
                    b.Navigation("SeatCounts");
                });
#pragma warning restore 612, 618
        }
    }
}
